apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-annotations.fullname" . }}
  labels:
    {{- include "grafana-annotations.labels" . | nindent 4 }}
  annotations:
  {{- if not .Values.serviceMonitor.create }}
    prometheus.io/scrape: "true"
  {{- end }}
  {{- if .Values.service.annotations }}
{{ .Values.service.annotations | toYaml | indent 4}}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grafana-annotations.selectorLabels" . | nindent 4 }}
